#Database Configuration
db:
  driver: org.h2.Driver
  url: jdbc:h2:file:${h2db.path}
  username: sa
  password: sa
 
#Hibernate Configuration
hibernate:
  dialect: org.hibernate.dialect.H2Dialect
  ejb.naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
  show_sql: true
  format_sql: true
  hbm2ddl.auto: update
#hibernate.hbm2ddl.auto=create-drop